version: "3.8"

services:
  productsdb:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_DB=products
    ports:
      - "5432:5432"
    volumes:
     - db:/var/lib/postgresql/data
  catalogapi:
    build:
      context: .
      dockerfile: src/Catalog.API/Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8090
      ConnectionStrings:CatalogDb: Server=productsdb;Port=5432;User Id=root;Password=S3cret;Database=products;
    ports:
      - "8090:8090"
    depends_on:
      - productsdb
  orderapi:
    build:
      context: .
      dockerfile: src/Order.API/Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8091
      ConnectionStrings:CatalogDb: Server=productsdb;Port=5432;User Id=root;Password=S3cret;Database=products;
      ProductBaseUrl: http://catalogapi:8090/
    ports:
      - "8091:8091"
    depends_on:
      - productsdb
      

volumes:
  db: 